Modify &fight to make developers do twice as much damage
FRCDiscord/Dozer pull request #210
Opened 2020-11-06 17:38 UTC by bkeeneykid

2020-11-06 17:39 UTC, tweirtx approved these changes
lmao im down

2020-11-06 17:39 UTC, AidanFromProgramming commented
Thats too good

2020-11-06 17:47 UTC, tweirtx approved these changes

2020-11-06 23:36 UTC, octocynth requested changes
😂 One little fix, and then I'll look forward to seeing this in action!

2020-11-06 23:36 UTC, octocynth commented on dozer/cogs/fun.py
> +            if players[turn].id in ctx.bot.config['developers'] or players[turn].id == ctx.me:
Should this be `players[turn] == ctx.me` or `players[turn].id == ctx.me.id`?

2020-11-07 00:31 UTC, octocynth approved these changes

2020-11-07 00:39 UTC, tweirtx approved these changes

2020-11-07 00:52 UTC, merged