Reaction roles
FRCDiscord/Dozer pull request #226
Opened 2020-11-26 23:33 UTC by AidanFromProgramming

Added reaction roles

close#160

2020-11-26 23:35 UTC, tweirtx submitted a review, later dismissed

2020-11-27 17:16 UTC, tweirtx submitted a review, later dismissed

2020-11-28 22:41 UTC, open-sourceress requested changes

2020-11-28 22:41 UTC, open-sourceress commented on dozer/cogs/roles.py
> +        reaction_roles = await ReactionRole.get_by(message_id=message_id, reaction=reaction)
This might need to be cached with `db.ConfigCache`, since reactions are added and removed frequently.

2020-11-28 22:41 UTC, open-sourceress commented on dozer/cogs/roles.py
> +    """
Roles can also be provided by name or by ID. These examples should include those formats so users know they don't have to mention a giveable role (which could have quite a few members) to add it to a menu.

2020-11-28 22:41 UTC, open-sourceress commented on dozer/cogs/roles.py
> +        e.add_field(name='Success!', value=f"I removed {role.mention} to message {shortcut}")
Should this say removed from?

2020-11-28 22:41 UTC, open-sourceress commented on dozer/cogs/roles.py
> +            raise BadArgument("Cannot give @\N{ZERO WIDTH SPACE}everyone for a level")
"For a level" should probably be something different.

2020-11-29 00:09 UTC, open-sourceress submitted a review, later dismissed

2020-11-29 00:13 UTC, open-sourceress approved these changes

2020-11-29 00:14 UTC, tweirtx approved these changes

2020-11-29 00:14 UTC, merged