Added reaction based deletes for the giveme command
FRCDiscord/Dozer pull request #240
Opened 2020-12-01 15:15 UTC by AidanFromProgramming

Close #239

2020-12-01 15:22 UTC, tweirtx submitted a review, later dismissed

2020-12-04 23:28 UTC, open-sourceress requested changes

2020-12-04 23:28 UTC, open-sourceress commented on dozer/cogs/roles.py
> +        await msg.add_reaction("❌")
This needs error handling in case Dozer doesn't have Add Reactions permissions, or the user has blocked the bot.

2020-12-04 23:28 UTC, open-sourceress commented on dozer/cogs/roles.py
> +            await msg.clear_reactions()
These two need to handle the case where the bot doesn't have Manage Message permissions as well.

2020-12-04 23:37 UTC, open-sourceress approved these changes

2020-12-05 18:08 UTC, tweirtx approved these changes

2020-12-05 18:09 UTC, merged