Allow &purge to accept message ID
FRCDiscord/Dozer pull request #254
Opened 2020-12-09 20:29 UTC by bkeeneykid

Closes #253

2020-12-09 20:35 UTC, tweirtx approved these changes

2020-12-09 20:35 UTC, AidanFromProgramming requested changes

2020-12-09 20:35 UTC, AidanFromProgramming commented on dozer/cogs/moderation.py
> +MAX_PURGE = 10000
I'd say thats a tad bit too high imo, maybe 1000 or less would be more reasonable as we just saw what 1000 looked like

2020-12-09 21:26 UTC, AidanFromProgramming approved these changes

2020-12-10 16:10 UTC, tweirtx approved these changes

2020-12-10 16:10 UTC, merged