Custion join leave
FRCDiscord/Dozer pull request #268
Opened 2021-01-01 19:46 UTC by AidanFromProgramming

Added the ability to have custom join leave messages, and brought the memberlogconfig table up to current db standards

Must run these sql query's before update
`alter table memberlogconfig rename column memberlog_channel to channel_id;

alter table memberlogconfig alter column channel_id drop not null;

alter table memberlogconfig drop column name;

alter table memberlogconfig
    add ping boolean default False;

alter table memberlogconfig
    add join_message text default null;

alter table memberlogconfig
    add leave_message text default null;`

2021-01-01 20:26 UTC, devyntk commented
Why bother changing `memberlog_channel` to `channel_id`? Also, why are you removing the `not null` constraint on the channel_id? The channel id should _never_ be null. I'll review the code once you comment on this. 

Also, like I've expressed in the past, I do believe these DB updates should be automated instead of being done manually right now. There is already a significant amount of work in `db.py` to do so.

2021-01-01 20:33 UTC, AidanFromProgramming commented
I am changing memberlog_channel to channel_id for the sake of consistency across all the other tables, and removing the not null constraint to allow for the disabling of member logging(which I just realized I never added, will add in just a bit) without removing the existing templates

2021-01-02 03:33 UTC, tweirtx requested changes
Undelete the other files

2021-01-02 03:33 UTC, tweirtx commented on dozer/cogs/actionlogs.py
> +            e.add_field(name='Success!', value=f"Join message template has been set too\n{template}")
Set "to" would be more correct than "set too"

2021-01-02 03:33 UTC, tweirtx commented on dozer/cogs/actionlogs.py
> +            e.add_field(name='Success!', value=f"Leave message template has been set too\n{template}")
Same as above

2021-01-02 03:40 UTC, tweirtx approved these changes

2021-01-02 23:40 UTC, tweirtx approved these changes

2021-01-14 18:50 UTC, devyntk approved these changes

2021-01-14 18:50 UTC, devyntk commented on dozer/cogs/actionlogs.py
> +    async def help(self, ctx):  # I cannot put formatting example in example_usage because then it trys to format the example
You can use double curly brackets to print literal curly brackets in `format` or f-strings. Read more https://docs.python.org/3/library/string.html#format-string-syntax

2021-01-14 18:50 UTC, devyntk commented on dozer/cogs/actionlogs.py
> +                join_message=template
This (and the same for `setleavemessage`) can likely be simplified using the python `or` operator, so you only have to make the `config` variable once and set `join_message=template or CustomJoinLeaveMessages.nullify` to set it to the appropriate value. This is not a issue that will block merging though.

2021-01-15 02:56 UTC, tweirtx approved these changes

2021-01-15 02:56 UTC, merged