Update documentation
FRCDiscord/Dozer pull request #326
Opened 2021-04-18 16:38 UTC by tweirtx

2021-04-18 16:40 UTC, AidanFromProgramming requested changes
Can we please add the documentation to the gitignore, and have dozer autoupdate docs when &update is run

2021-04-18 16:40 UTC, tweirtx commented
Nope, because thanks to Spectrum the docs have to be served from another server

2021-05-27 16:07 UTC, devyntk approved these changes

2021-06-12 17:17 UTC, AidanFromProgramming approved these changes

2021-06-12 17:18 UTC, merged