Add shortcuts cog
FRCDiscord/Dozer pull request #430
Opened 2023-04-14 07:31 UTC by abidingabi

This cog replaces the MEE6 functionality of providing simple text shortcuts.

Below is a demonstration of its usage:
![image](https://user-images.githubusercontent.com/16172089/229324170-180b5c99-a040-42a0-9ae2-d94853d62f9e.png)
![image](https://user-images.githubusercontent.com/16172089/229324172-92a9d570-1315-4baf-b37f-f4e92a193863.png)

(This is an exact duplicate of #425 code-wise, I had to move some things around though which caused that PR to no longer be valid.)

2023-04-16 21:19 UTC, guineawheek approved these changes
verified to work on the ftc discord

2023-04-17 01:08 UTC, JayFromProgramming requested changes

2023-04-17 01:08 UTC, JayFromProgramming commented on dozer/cogs/shortcuts.py
> +    async def setprefix(self, ctx, prefix):
This is going to conflict with dozers already existing setprefix command

2023-04-17 01:11 UTC, JayFromProgramming approved these changes

2023-04-17 01:42 UTC, tweirtx approved these changes

2023-04-17 01:42 UTC, merged