Add frcrule command
FRCDiscord/Dozer pull request #454
Opened 2023-11-21 18:04 UTC by GrahamSH-LLK

![image](https://github.com/FRCDiscord/Dozer/assets/64214252/60f42e37-b5ac-4e49-9b46-38c0bcf5d282)

2023-11-21 18:10 UTC, devyntk approved these changes

2023-11-21 19:34 UTC, GrahamSH-LLK commented on dozer/cogs/firstqa.py
> +           await ctx.send("Not a valid rule.", ephemeral=True)
Regex is added!

2023-11-21 19:34 UTC, GrahamSH-LLK commented
![image](https://github.com/FRCDiscord/Dozer/assets/64214252/abe35480-3a5e-485a-8379-9da4ddaa1110)

2023-11-21 19:42 UTC, GrahamSH-LLK commented
![image](https://github.com/FRCDiscord/Dozer/assets/64214252/e5425264-7cad-42a2-80f8-cdaf96a084bd)
switched to embed

2023-11-21 20:32 UTC, devyntk requested changes

2023-11-21 20:32 UTC, devyntk commented on .gitpod.yml
> +# This configuration file was automatically generated by Gitpod.
This file shouldn't be here.

2023-11-21 20:32 UTC, devyntk commented on dozer/cogs/firstqa.py
> +        if not re.match(r'^[a-zA-Z]\d{3}$', rule):
If we're already using regex, I would much rather use regex groups to capture the letter and number part of the rule. Example using named groups: `^(?<letter>[a-zA-Z])(?<number>\d{3})$`

2023-11-21 20:32 UTC, devyntk commented on dozer/cogs/firstqa.py
> +            async with ctx.cog.ses.get('https://firstfrc.blob.core.windows.net/frc2023/Manual/HTML/2023FRCGameManual.htm') as response:
I don't love hard coding this to a specific year's game manual. When this becomes 2024, it requires manual input to switch this URL. The URL before, while it has the manual embedded inside of an iframe, is year-agnostic. I have no problem with the bs4 scraping, especially for something like this, but we should keep this year agnostic.

2023-11-21 20:32 UTC, devyntk commented on dozer/cogs/firstqa.py
> +            url=f"https://frc-qa.firstinspires.org/manual/rule/{letter_part.upper()}/{number_part}",
We shouldn't display any data before doing the validation of it. This URL could be broken if it doesn't exist or adhere to the regex we have. The error state and happy path embeds should be entirely different (and ideally the unhappy path embed is ephemeral like you had earlier).

2023-11-21 20:33 UTC, devyntk commented on dozer/cogs/firstqa.py
> +    async def frcrule(self, ctx: DozerContext, rule: str):
Also, this function needs a docstring, as the CI lint is failing.

2023-11-22 03:40 UTC, devyntk commented
Couple last things:
Still a few more linting errors - I have to run these manually now but feel free to run pylint locally instead. I can't merge until there's no lint failures. 
Another nit that you by all means don't have to implement: Removing the new lines so that it flows in one paragraph would be nice, it appears a bit weird from your screenshots to have new lines in odd places. This should be as easy as calling `.replace(/n,"")` on your summary, but please check this with more complicated rules before pushing it. 

Thanks for this patience on this - just about over the finish line!

2023-11-22 12:18 UTC, GrahamSH-LLK commented
I fixed the lint errors, I'm going to take a look at the newline stripping later today.

2023-11-22 15:17 UTC, devyntk approved these changes
The way of getting the URL of the manual here is a bit hacky but that's fine - works for me!

2023-11-22 18:36 UTC, merged